#output "kubectl_config" {
#  description = "kubectl config as generated by the module."
#  value       = module.eks.kubeconfig
#}
#output "config_map_aws_auth" {
#  description = "A kubernetes configuration to authenticate to this EKS cluster."
#  value       = module.eks.config_map_aws_auth
#}
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}
output "cluster_name" {
  value = var.cluster_name
}
output "host" {
  value = data.aws_eks_cluster.eks.endpoint
}

#output "cluster_ca_certificate" {
#  value = data.aws_eks_cluster.eks.certificate_authority.0.data
#}

output "lambda_role_arn" {
  value = aws_iam_role.lambda_cdo_role.arn
}
output "lambda_remove_role_arn" {
  value = aws_iam_role.lambda_cdo_remove_role.arn
}

output "eks_private_key" {
  value     = tls_private_key.eks.private_key_pem
  sensitive = true
}
